### Clients 조회
GET http://localhost:3000/api/clients

### Clients 생성
POST http://localhost:3000/api/clients
Content-Type: application/json

{
    "client": "TEST",
    "accessNo": 13496039
}

### Clients 수정
PUT http://localhost:3000/api/clients/112
Content-Type: application/json

{
    "client": "TEST",
    "accessNo": 13496037
}

### Clients 삭제
DELETE http://localhost:3000/api/clients/112



### Balance 게시글 전체 조회
GET http://localhost:3000/api/balances