### Clients 조회
GET http://localhost:3000/api/clients

### Clients 생성
POST http://localhost:3000/api/clients
Content-Type: application/json

{
    "client": "TEST",
    "accessNo": 13496039
}

### Clients 수정
PUT http://localhost:3000/api/clients/15
Content-Type: application/json

{
    "client": "TEST",
    "accessNo": 13496039
}




### Balance 게시글 전체 조회
GET http://localhost:3000/api/balances