### Clients 조회
GET http://localhost:3000/api/clients

### Clients 생성
POST http://localhost:3000/api/clients
Content-Type: application/json

{
    "client": "TEST",
    "accessNo": 13496039
}

### Clients 수정
PUT http://localhost:3000/api/clients/112
Content-Type: application/json

{
    "client": "TEST",
    "accessNo": 13496037
}

### Clients 삭제
DELETE http://localhost:3000/api/clients/112



### Balance 조회
GET http://localhost:3000/api/balances/1

### Balance 생성
POST http://localhost:3000/api/balances/1
Content-Type: application/json

{
  "date": "2022-01-01",
  "content": "3월 선결제 금액",
  "in_charge": "홍길동",
  "amount": 2648000
}

### Balance 수정
PUT http://localhost:3000/api/balances/2
Content-Type: application/json

{
  "date": "2022-01-01",
  "content": "3월 선결제 금액",
  "in_charge": "홍길동",
  "amount": 2648000
}

### Balance 삭제
DELETE http://localhost:3000/api/balances/2


### Login 시도
GET http://localhost:3000/api/user


### Login
POST http://localhost:3000/api/users/login
Content-Type: application/json

{ 
  "id": "sampleid",
  "pw": "samplepwd"
}

### Admin Login
POST http://localhost:3000/api/users/login
Content-Type: application/json

{ 
  "id": "nemolab",
  "pw": "adminpwd"
}

### Logout
POST http://localhost:3000/api/users/logout
Content-Type: application/json